"""Step 1 — Exploratory data analysis.

Writes reports/01_eda.md and figures under reports/figures/.
Run: uv run python src/01_eda.py
"""

import re
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import NearestNeighbors

ROOT = Path(__file__).resolve().parents[1]
REPORTS = ROOT / "reports"
FIGS = REPORTS / "figures"
FIGS.mkdir(parents=True, exist_ok=True)
RNG = np.random.default_rng(0)

LABELS = ["Bug fix", "Feature dev", "Refactoring", "Architecting", "Researching",
          "Testing", "Review", "Optimize", "Setup", "Other"]
# Holdout support published in TASK.md (DistilBERT table).
HOLDOUT_SUPPORT = {"Bug fix": 885, "Feature dev": 1381, "Refactoring": 262, "Architecting": 247,
                   "Researching": 1221, "Testing": 128, "Review": 171, "Optimize": 49,
                   "Setup": 316, "Other": 1539}
HARD_PAIRS = [("Refactoring", "Optimize"), ("Review", "Researching"), ("Architecting", "Feature dev"),
              ("Setup", "Bug fix"), ("Bug fix", "Feature dev"), ("Researching", "Other"),
              ("Testing", "Feature dev")]

out: list[str] = []


def md(s: str = "") -> None:
    out.append(s)


def table(df: pd.DataFrame, floatfmt: str = ".3f") -> None:
    md(df.to_markdown(floatfmt=floatfmt))
    md()


# ---------------------------------------------------------------- load
train = pd.read_json(ROOT / "train.jsonl", lines=True)
hold = pd.read_json(ROOT / "holdout.jsonl", lines=True)

md("# Step 1 — EDA report")
md()
md("Generated by `src/01_eda.py`.")
md()

# ---------------------------------------------------------------- 1. integrity
md("## 1. Integrity")
md()
integ = pd.DataFrame({
    "rows": [len(train), len(hold)],
    "null text": [train.text.isna().sum(), hold.text.isna().sum()],
    "empty/blank text": [(train.text.str.strip() == "").sum(), (hold.text.str.strip() == "").sum()],
    "duplicate ids": [train.id.duplicated().sum(), hold.id.duplicated().sum()],
    "duplicate texts": [train.text.duplicated().sum(), hold.text.duplicated().sum()],
}, index=["train", "holdout"])
table(integ)
unknown = set(train.label) - set(LABELS)
md(f"- Labels outside the 10 names: {sorted(unknown) or 'none'}")
md(f"- id overlap train∩holdout: {len(set(train.id) & set(hold.id))}")
exact_overlap = hold.text.isin(set(train.text))
md(f"- Holdout rows whose exact text appears in train: {exact_overlap.sum()} "
   f"({exact_overlap.mean():.1%})")
md(f"- id prefixes: train {train.id.str.rsplit('-', n=1).str[0].value_counts().to_dict()}, "
   f"holdout {hold.id.str.rsplit('-', n=1).str[0].value_counts().to_dict()}")
md()

# ---------------------------------------------------------------- 2. labels
md("## 2. Label distribution")
md()
dist = pd.DataFrame({
    "train n": train.label.value_counts().reindex(LABELS),
    "train %": train.label.value_counts(normalize=True).reindex(LABELS) * 100,
    "holdout n (TASK.md)": pd.Series(HOLDOUT_SUPPORT),
})
dist["holdout %"] = dist["holdout n (TASK.md)"] / dist["holdout n (TASK.md)"].sum() * 100
dist = dist.sort_values("train n", ascending=False)
table(dist, ".1f")
md(f"Imbalance ratio largest/smallest class: {dist['train n'].max() / dist['train n'].min():.0f}×")
md()

fig, ax = plt.subplots(figsize=(8, 4))
x = np.arange(len(dist))
ax.bar(x - 0.2, dist["train %"], 0.4, label="train")
ax.bar(x + 0.2, dist["holdout %"], 0.4, label="holdout (published support)")
ax.set_xticks(x, dist.index, rotation=35, ha="right")
ax.set_ylabel("% of rows")
ax.legend()
fig.tight_layout()
fig.savefig(FIGS / "01_label_distribution.png", dpi=120)
plt.close(fig)
md("![labels](figures/01_label_distribution.png)")
md()

# ---------------------------------------------------------------- 3. text shape
md("## 3. Text shape")
md()
CODE_RE = re.compile(r"```|^\s{4,}\S|[{};]\s*$|\bdef \w+\(|\bfunction\b|\bimport \w|#include|=>|\bclass \w+",
                     re.M)
TRACE_RE = re.compile(r"Traceback \(most recent call last\)|\bat [\w.$]+\(.*:\d+\)|Error:|Exception|"
                      r"\berror\b.*line \d+|\bstack trace\b|npm ERR!|\bFAILED\b", re.I)
URL_RE = re.compile(r"https?://")


def featurize(df: pd.DataFrame) -> pd.DataFrame:
    t = df.text
    f = pd.DataFrame(index=df.index)
    f["chars"] = t.str.len()
    f["words"] = t.str.split().str.len()
    f["approx_tokens"] = (f.chars / 4).round()  # ~4 chars per subword token for English/code
    f["lines"] = t.str.count("\n") + 1
    f["has_code"] = t.str.contains(CODE_RE)
    f["has_trace"] = t.str.contains(TRACE_RE)
    f["has_url"] = t.str.contains(URL_RE)
    letters = t.str.count(r"[^\W\d_]")
    f["non_ascii_letter_frac"] = t.str.count(r"[^\x00-\x7F]") / letters.clip(lower=1)
    f["non_english"] = f.non_ascii_letter_frac > 0.3
    return f


ftr = featurize(train)
fho = featurize(hold)
md("Length (overall):")
md()
table(pd.DataFrame({"train": ftr[["chars", "words", "approx_tokens", "lines"]].describe(
    percentiles=[.5, .9, .95, .99]).T["50%"],
                    "train p90": ftr[["chars", "words", "approx_tokens", "lines"]].quantile(.9),
                    "train p99": ftr[["chars", "words", "approx_tokens", "lines"]].quantile(.99),
                    "holdout median": fho[["chars", "words", "approx_tokens", "lines"]].median(),
                    "holdout p90": fho[["chars", "words", "approx_tokens", "lines"]].quantile(.9)}).rename(
    columns={"train": "train median"}), ".0f")
for lim in (128, 256, 512, 1024):
    md(f"- Rows with ≈>{lim} tokens: train {(ftr.approx_tokens > lim).mean():.1%}, "
       f"holdout {(fho.approx_tokens > lim).mean():.1%}")
md()

per = ftr.assign(label=train.label).groupby("label").agg(
    n=("chars", "size"), median_words=("words", "median"), p90_words=("words", lambda s: s.quantile(.9)),
    over_256_tok=("approx_tokens", lambda s: (s > 256).mean()),
    has_code=("has_code", "mean"), has_trace=("has_trace", "mean"), has_url=("has_url", "mean"),
    non_english=("non_english", "mean")).reindex(LABELS)
md("Per class (fractions are share of rows):")
md()
table(per, ".2f")
md(f"Holdout content flags: code {fho.has_code.mean():.2f}, trace {fho.has_trace.mean():.2f}, "
   f"url {fho.has_url.mean():.2f}, non-English {fho.non_english.mean():.2f} "
   f"(train: {ftr.has_code.mean():.2f}, {ftr.has_trace.mean():.2f}, {ftr.has_url.mean():.2f}, "
   f"{ftr.non_english.mean():.2f})")
md()

fig, ax = plt.subplots(figsize=(8, 4.5))
data = [np.log10(ftr.words[train.label == lab].clip(lower=1)) for lab in LABELS]
ax.boxplot(data, tick_labels=LABELS, showfliers=False)
ax.set_ylabel("log10(words)")
ax.tick_params(axis="x", rotation=35)
fig.tight_layout()
fig.savefig(FIGS / "01_length_by_class.png", dpi=120)
plt.close(fig)
md("![length](figures/01_length_by_class.png)")
md()

# ---------------------------------------------------------------- 4. label consistency
md("## 4. Label consistency (noise ceiling signals)")
md()


def norm(s: pd.Series) -> pd.Series:
    return s.str.lower().str.replace(r"\s+", " ", regex=True).str.strip()


train["norm"] = norm(train.text)
grp = train.groupby("norm").label.agg(["size", "nunique"])
dup_groups = grp[grp["size"] > 1]
md(f"- Normalized-text duplicate groups in train: {len(dup_groups)} "
   f"covering {dup_groups['size'].sum()} rows; groups with conflicting labels: "
   f"{(dup_groups['nunique'] > 1).sum()} ({(dup_groups['nunique'] > 1).mean():.1%} of groups)")
conf = train[train.norm.isin(dup_groups[dup_groups['nunique'] > 1].index)]
if len(conf):
    md()
    md("Examples of identical text with different labels:")
    md()
    for t, g in list(conf.groupby("norm"))[:8]:
        md(f"- `{t[:120]!s}` → {sorted(g.label.unique())}")
md()

# Near-duplicates: nearest train neighbour (TF-IDF cosine), label agreement by similarity bucket.
vec = TfidfVectorizer(ngram_range=(1, 2), min_df=2, sublinear_tf=True)
Xtr = vec.fit_transform(train.text)
Xho = vec.transform(hold.text)
nn = NearestNeighbors(n_neighbors=2, metric="cosine").fit(Xtr)
dist_tr, idx_tr = nn.kneighbors(Xtr)
# first neighbour is the row itself (or an exact duplicate); take the first that is a different row
self_first = idx_tr[:, 0] == np.arange(len(train))
nb = np.where(self_first, idx_tr[:, 1], idx_tr[:, 0])
sim = 1 - np.where(self_first, dist_tr[:, 1], dist_tr[:, 0])
agree = train.label.values == train.label.values[nb]
buckets = pd.cut(sim, [0, .3, .5, .7, .8, .9, .95, 1.0001], right=False)
nn_tab = pd.DataFrame({"bucket": buckets, "agree": agree}).groupby("bucket", observed=True).agg(
    rows=("agree", "size"), label_agreement=("agree", "mean"))
md("Nearest-neighbour label agreement in train (TF-IDF 1–2-gram cosine):")
md()
table(nn_tab)
hi = sim >= 0.9
md(f"- Rows with a near-duplicate (cos ≥ 0.9): {hi.sum()} ({hi.mean():.1%}); of these, label disagrees "
   f"in {(~agree[hi]).mean():.1%}.")
md("- Label disagreement among near-duplicates is a lower bound on teacher inconsistency.")
md()
nd = pd.DataFrame({"a": train.label.values, "b": train.label.values[nb]})[hi & ~agree]
if len(nd):
    pairs = nd.apply(lambda r: " / ".join(sorted([r.a, r.b])), axis=1).value_counts().head(12)
    md("Most frequent conflicting label pairs among near-duplicates (cos ≥ 0.9):")
    md()
    table(pairs.rename("count").to_frame(), ".0f")
    md("Examples:")
    md()
    shown = 0
    for i in np.where(hi & ~agree)[0]:
        if i < nb[i]:
            a, b = train.iloc[i], train.iloc[nb[i]]
            md(f"- **{a.label}**: `{a.text[:160].replace(chr(10), ' ')}`  ")
            md(f"  **{b.label}**: `{b.text[:160].replace(chr(10), ' ')}`  (cos {sim[i]:.2f})")
            shown += 1
        if shown >= 8:
            break
    md()

d_ho, i_ho = nn.kneighbors(Xho, n_neighbors=1)
sim_ho = 1 - d_ho[:, 0]
md(f"- Holdout rows with a train near-duplicate (cos ≥ 0.9): {(sim_ho >= .9).mean():.1%}; "
   f"cos ≥ 0.7: {(sim_ho >= .7).mean():.1%}. Median holdout→train similarity {np.median(sim_ho):.2f} "
   f"(train→train {np.median(sim):.2f}).")
md()

# ---------------------------------------------------------------- 5. ordering / conversation structure
md("## 5. Row order — are prompts grouped by conversation?")
md()
p = train.label.value_counts(normalize=True)
chance = (p ** 2).sum()
same_prev = (train.label == train.label.shift()).iloc[1:].mean()
md(f"- P(label == previous row's label) = {same_prev:.3f}; expected if order were random = {chance:.3f}.")
perm = train.label.sample(frac=1, random_state=0).reset_index(drop=True)
md(f"- Same statistic after shuffling rows: {(perm == perm.shift()).iloc[1:].mean():.3f}.")
adj_sim_tr = np.asarray(Xtr[1:].multiply(Xtr[:-1]).sum(axis=1)).ravel()
rand_idx = RNG.permutation(len(train))
rnd_sim = np.asarray(Xtr[rand_idx[1:]].multiply(Xtr[rand_idx[:-1]]).sum(axis=1)).ravel()
adj_sim_ho = np.asarray(Xho[1:].multiply(Xho[:-1]).sum(axis=1)).ravel()
md(f"- Mean TF-IDF cosine between consecutive rows: train {adj_sim_tr.mean():.3f}, holdout "
   f"{adj_sim_ho.mean():.3f}, random pairs {rnd_sim.mean():.3f}.")
by_class = pd.DataFrame({"label": train.label.iloc[1:].values,
                         "same_as_prev": (train.label == train.label.shift()).iloc[1:].values}).groupby(
    "label").same_as_prev.mean().reindex(LABELS)
md()
md("P(same label as previous row) per class:")
md()
table(by_class.rename("P(same as prev)").to_frame())
# Do holdout rows come from the same conversations, in the same global order?
hpos = np.arange(len(hold)) / len(hold)
tpos = i_ho[:, 0] / len(train)
conf_m = sim_ho > 0.3
rho = pd.Series(hpos).corr(pd.Series(tpos), method="spearman")
md(f"- Holdout position vs position of its nearest train row (relative 0–1): Spearman ρ = {rho:.2f}; "
   f"for confident matches (cos > 0.3, n={conf_m.sum()}) the median position gap is "
   f"{np.median(np.abs(tpos[conf_m] - hpos[conf_m])):.3f} of the file.")
gap = np.abs(tpos - hpos)
null_gaps = []
for s in range(20):  # null: same matches, holdout row order shuffled
    hp = RNG.permutation(len(hold)) / len(hold)
    null_gaps.append([(np.abs(tpos - hp)[conf_m] <= w).mean() for w in (.01, .02, .05)])
null_gaps = np.mean(null_gaps, axis=0)
md("- Share of confident matches whose train neighbour lies within ±1% / ±2% / ±5% of the holdout row's "
   f"relative position: observed {', '.join(f'{(gap[conf_m] <= w).mean():.1%}' for w in (.01, .02, .05))}; "
   f"if holdout order were unrelated to train order (holdout shuffled, 20 runs): "
   f"{', '.join(f'{v:.1%}' for v in null_gaps)}.")
md("- ⇒ Both files keep the original order and holdout rows were sampled out of the same "
   "conversations. Many holdout prompts have conversational neighbours in train.")
md()
fig, ax = plt.subplots(figsize=(5, 5))
ax.scatter(hpos[conf_m], tpos[conf_m], s=2, alpha=.4)
ax.set_xlabel("holdout row position (relative)")
ax.set_ylabel("nearest train row position (relative)")
ax.set_title("Holdout ↔ train alignment (cos > 0.3)")
fig.tight_layout()
fig.savefig(FIGS / "01_holdout_train_alignment.png", dpi=120)
plt.close(fig)
md("![alignment](figures/01_holdout_train_alignment.png)")
md()
md("Sample of consecutive train rows (id, label, text start):")
md()
start = 200
for _, r in train.iloc[start:start + 12].iterrows():
    md(f"- `{r.id}` **{r.label}** — {r.text[:110].replace(chr(10), ' ')!s}")
md()

# ---------------------------------------------------------------- 6. hard pairs: discriminative terms
md("## 6. Hard pairs — most discriminative words")
md()
md("Smoothed log-odds ratio (informative Dirichlet prior, Monroe et al. 2008) on unigrams+bigrams.")
md()
cv_vec = TfidfVectorizer(ngram_range=(1, 2), min_df=5, use_idf=False, norm=None, binary=True,
                         token_pattern=r"(?u)\b[a-zA-Z][a-zA-Z_]+\b")
B = cv_vec.fit_transform(train.text)
vocab = np.array(cv_vec.get_feature_names_out())
prior = np.asarray(B.sum(axis=0)).ravel() + 0.01
a0 = prior.sum()
for a, b in HARD_PAIRS:
    ya = np.asarray(B[(train.label == a).values].sum(axis=0)).ravel()
    yb = np.asarray(B[(train.label == b).values].sum(axis=0)).ravel()
    na, nb_ = ya.sum(), yb.sum()
    delta = (np.log((ya + prior) / (na + a0 - ya - prior)) - np.log((yb + prior) / (nb_ + a0 - yb - prior)))
    var = 1 / (ya + prior) + 1 / (yb + prior)
    z = delta / np.sqrt(var)
    top_a = vocab[np.argsort(-z)[:15]]
    top_b = vocab[np.argsort(z)[:15]]
    md(f"**{a}** vs **{b}**")
    md()
    md(f"- → {a}: {', '.join(top_a)}")
    md(f"- → {b}: {', '.join(top_b)}")
    for kw in {"Refactoring": ["refactor", "faster", "performance"], "Review": ["review", "explain"],
               "Architecting": ["design", "architecture"], "Setup": ["install", "error"]}.get(a, []):
        has = train.text.str.contains(rf"\b{kw}", case=False)
        md(f"  - rows containing `{kw}`: {a} {has[train.label == a].mean():.1%} vs "
           f"{b} {has[train.label == b].mean():.1%}; label mix of rows with it: "
           f"{train.label[has].value_counts(normalize=True).head(4).round(2).to_dict()}")
    md()

md("Prompt templates that repeat many times (label mix):")
md()
for pat in [r"I will provide you with a passage", r"task implement|following feature"]:
    s = train[train.text.str.contains(pat, case=False, regex=True)]
    md(f"- `{pat}`: {len(s)} rows → {s.label.value_counts().to_dict()}")
md()

# ---------------------------------------------------------------- 7. samples
md("## 7. Random samples per class")
md()
for lab in LABELS:
    md(f"### {lab}")
    md()
    for t in train[train.label == lab].text.sample(6, random_state=1):
        md(f"- {t[:220].replace(chr(10), ' ')!s}{'…' if len(t) > 220 else ''}")
    md()

(REPORTS / "01_eda.md").write_text("\n".join(out))
print("\n".join(out))
