"""Step 1b — Label counts and top TF-IDF n-grams per label.

For each label a separate TF-IDF vectorizer is fitted on that label's texts only, once per n-gram order
(1, 2, 3). Terms are ranked by their mean TF-IDF weight across the label's documents. English stop words
are removed, otherwise every list is "the / to / of".

Because the IDF is computed inside the class, a term that is frequent in *every* class can still rank high.
A second table ranks terms with one vectorizer fitted on all of train, by (mean weight in class − mean
weight in the other classes), which shows what is *distinctive* for each label.

Writes reports/01b_label_ngrams.md. Run: uv run python src/01b_label_ngrams.py
"""

from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

ROOT = Path(__file__).resolve().parents[1]
LABELS = ["Bug fix", "Feature dev", "Refactoring", "Architecting", "Researching",
          "Testing", "Review", "Optimize", "Setup", "Other"]
TOP_K = 10
# Words only (≥2 chars), so pasted code symbols and numbers do not dominate.
TOKEN_PATTERN = r"(?u)\b[^\W\d_][^\W\d_]+\b"

train = pd.read_json(ROOT / "train.jsonl", lines=True)
out: list[str] = ["# Step 1b — Label counts and top n-grams per label", "",
                  "Generated by `src/01b_label_ngrams.py`.", ""]

# ---------------------------------------------------------------- label counts
counts = train.label.value_counts().reindex(LABELS).sort_values(ascending=False)
tab = pd.DataFrame({"label": counts.index, "number of examples": counts.values,
                    "percentage": (counts.values / len(train) * 100).round(2)})
tab.loc[len(tab)] = ["Total", counts.sum(), 100.0]
out += ["## Label counts (train)", "", tab.to_markdown(index=False), ""]


def top_terms_within_class(texts: pd.Series, n: int) -> list[str]:
    vec = TfidfVectorizer(ngram_range=(n, n), stop_words="english", token_pattern=TOKEN_PATTERN,
                          sublinear_tf=True, min_df=2)
    X = vec.fit_transform(texts)
    mean_w = np.asarray(X.mean(axis=0)).ravel()
    terms = vec.get_feature_names_out()
    return list(terms[np.argsort(-mean_w)[:TOP_K]])


rows = []
for lab in counts.index:
    texts = train.text[train.label == lab]
    rows.append({"label": lab, **{f"top-10 {name}": ", ".join(top_terms_within_class(texts, n))
                                  for n, name in [(1, "unigram"), (2, "bi-gram"), (3, "tri-gram")]}})
out += ["## Top-10 n-grams per label — vectorizer fitted per label (as requested)", "",
        "Rank = mean TF-IDF weight over the label's documents; IDF from that label only; stop words removed.",
        "", pd.DataFrame(rows).to_markdown(index=False), ""]

# ---------------------------------------------------------------- distinctive version
rows = []
for n, name in [(1, "unigram"), (2, "bi-gram"), (3, "tri-gram")]:
    vec = TfidfVectorizer(ngram_range=(n, n), stop_words="english", token_pattern=TOKEN_PATTERN,
                          sublinear_tf=True, min_df=3)
    X = vec.fit_transform(train.text)
    terms = vec.get_feature_names_out()
    for lab in counts.index:
        m = (train.label == lab).values
        score = np.asarray(X[m].mean(axis=0)).ravel() - np.asarray(X[~m].mean(axis=0)).ravel()
        rows.append({"label": lab, "n": name, "terms": ", ".join(terms[np.argsort(-score)[:TOP_K]])})
dist = pd.DataFrame(rows).pivot(index="label", columns="n", values="terms").reindex(counts.index)
dist = dist[["unigram", "bi-gram", "tri-gram"]].add_prefix("top-10 ").reset_index()
out += ["## Top-10 distinctive n-grams per label — one vectorizer on all of train", "",
        "Rank = mean TF-IDF in the label − mean TF-IDF in all other labels.", "",
        dist.to_markdown(index=False), ""]

(ROOT / "reports" / "01b_label_ngrams.md").write_text("\n".join(out))
print("\n".join(out))
