"""Step 2 — Cross-validation folds and a sanity check of the evaluation protocol.

Folds: 5-fold StratifiedKFold (shuffled, seed 42) over train rows. A row-level random split mirrors how the
holdout was drawn (EDA §5: holdout rows were sampled row-by-row out of the same conversations), so CV
scores should be comparable to holdout scores.

Writes data/folds.csv (id, fold) and reports/02_folds.md.
Run: uv run python src/02_folds.py
"""

from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.model_selection import StratifiedKFold

from evaluation import LABELS, evaluate, plot_confusion, plot_curves, to_markdown

ROOT = Path(__file__).resolve().parents[1]
SEED = 42
N_FOLDS = 5

train = pd.read_json(ROOT / "train.jsonl", lines=True)
skf = StratifiedKFold(n_splits=N_FOLDS, shuffle=True, random_state=SEED)
train["fold"] = -1
for k, (_, va) in enumerate(skf.split(train.text, train.label)):
    train.loc[va, "fold"] = k
(ROOT / "data").mkdir(exist_ok=True)
train[["id", "fold"]].to_csv(ROOT / "data" / "folds.csv", index=False)

out = ["# Step 2 — Folds and evaluation protocol", "", "Generated by `src/02_folds.py`.", ""]
counts = pd.crosstab(train.label, train.fold).reindex(LABELS)
pct = (counts / counts.sum() * 100).round(2)
tab = counts.astype(str) + " (" + pct.astype(str) + "%)"
tab.columns = [f"fold {c}" for c in tab.columns]
tab["overall %"] = (train.label.value_counts(normalize=True) * 100).reindex(LABELS).round(2)
tab.loc["rows"] = list(counts.sum().astype(str)) + [""]
out += ["## Label distribution per fold (count, % of fold)", "", tab.to_markdown(), "",
        f"Max deviation of any class share from its overall share: "
        f"{(pct.sub(tab['overall %'].iloc[:-1].astype(float), axis=0)).abs().max().max():.2f} pp.", ""]

# Sanity check of the harness: a random classifier that guesses by class prior.
rng = np.random.default_rng(SEED)
prior = train.label.value_counts(normalize=True).reindex(LABELS).values
proba = rng.dirichlet(prior * 50, size=len(train))
pred = np.array(LABELS)[proba.argmax(1)]
res = evaluate(train.label, pred, proba)
plot_confusion(res["cm"], ROOT / "reports" / "figures" / "02_random_baseline_cm.png", "Random (prior) baseline")
plot_curves(train.label, proba, ROOT / "reports" / "figures" / "02_random_baseline_curves.png", "Random (prior) baseline")
out += ["## Harness sanity check — random classifier (should show AUC≈0.5, large p-values)", "",
        to_markdown(res, "Random baseline", "figures/02_random_baseline_cm.png",
                    "figures/02_random_baseline_curves.png")]

(ROOT / "reports" / "02_folds.md").write_text("\n".join(out))
print("\n".join(out))
