"""Block 8 — Error analysis: model errors vs teacher-label collisions (PLAN §8).

Uses the OOF probabilities of the current best model (default stack-C) and the Qwen3-8B-instr embeddings.

1. Confident learning (cleanlab): rows whose teacher label is likely inconsistent with the rest of the data.
2. Near-duplicate collisions: for each row, the most similar *other* train row (Qwen3-8B-instr cosine). If it is a
   near-duplicate (cos ≥ 0.95) and carries a different teacher label, the teacher itself disagrees on almost the
   same text.
3. Error attribution per class: every false negative / false positive is put in one bucket —
   (a) near-duplicate collision: a near-duplicate of the row has the teacher label the model predicted;
   (b) cleanlab label issue: the row's teacher label is flagged as likely inconsistent;
   (c) unexplained model error.
4. F1 per class on all rows vs on rows not flagged by (a)/(b) — how far the model is from the bar where the labels
   are self-consistent.
5. Samples of errors for the main confusion pairs of the weak classes, for reading by hand.

Writes reports/07_error_analysis.md. Run: uv run python src/07_error_analysis.py [exp_id]
"""

import sys

import numpy as np
import pandas as pd
from cleanlab.filter import find_label_issues
from sklearn.metrics import f1_score

from evaluation import LABELS
from experiments import DATA, REPORTS, load_data

EXP = sys.argv[1] if len(sys.argv) > 1 else "stack-C"
NEAR_DUP = 0.95
K = len(LABELS)
WEAK = ["Review", "Architecting", "Optimize", "Refactoring", "Setup", "Testing"]

train, _ = load_data()
y = train.y.values
P = np.load(DATA / "oof" / f"{EXP}.npy").astype(np.float64)
P = P / P.sum(1, keepdims=True)
pred = P.argmax(1)
out = [f"# Block 8 — Error analysis of `{EXP}`", "", "Generated by `src/07_error_analysis.py`.", ""]

# ---------------------------------------------------------------- 1. cleanlab
issues = find_label_issues(y, P, filter_by="prune_by_noise_rate", n_jobs=1)  # no worker processes: this script has no __main__ guard (macOS spawn would re-run it)
out += ["## 1. Confident learning (cleanlab, prune_by_noise_rate)", "",
        f"Rows flagged as likely label issues: **{issues.sum()} ({issues.mean():.1%})**.", ""]
tab = pd.DataFrame({"rows": np.bincount(y, minlength=K), "flagged": np.bincount(y[issues], minlength=K)},
                   index=LABELS)
tab["flagged %"] = (tab.flagged / tab.rows * 100).round(1)
out += [tab.to_markdown(), ""]
pairs = pd.Series([f"{LABELS[a]} → {LABELS[b]}" for a, b in zip(y[issues], pred[issues])]).value_counts().head(15)
out += ["Most frequent (teacher label → model's label) among flagged rows:", "",
        pairs.rename("rows").to_frame().to_markdown(), ""]

# ---------------------------------------------------------------- 2. near duplicates
E = np.load(DATA / "emb" / "qwen3-8b-instr" / "train.npy").astype(np.float32)
nn_idx = np.zeros(len(E), dtype=int)
nn_sim = np.zeros(len(E), dtype=np.float32)
for s in range(0, len(E), 2000):
    S = E[s:s + 2000] @ E.T
    S[np.arange(S.shape[0]), np.arange(s, s + S.shape[0])] = -1  # exclude self
    nn_idx[s:s + 2000] = S.argmax(1)
    nn_sim[s:s + 2000] = S.max(1)
nd = nn_sim >= NEAR_DUP
nn_lab = y[nn_idx]
agree = nn_lab == y
out += ["## 2. Near-duplicate collisions (Qwen3-8B-instr cosine)", "",
        f"Rows with a near-duplicate (cos ≥ {NEAR_DUP}) elsewhere in train: **{nd.sum()} ({nd.mean():.1%})**; "
        f"the near-duplicate has a **different** teacher label in **{(~agree[nd]).mean():.1%}** of them.", ""]
cons = pd.DataFrame({"rows with near-dup": np.bincount(y[nd], minlength=K),
                     "same label %": [(agree[nd & (y == c)]).mean() * 100 if (nd & (y == c)).any() else np.nan
                                      for c in range(K)]}, index=LABELS).round(1)
out += ["Teacher self-consistency per class (share of near-duplicates that carry the same label). "
        "A model that copies the nearest near-duplicate cannot beat this on those rows:", "",
        cons.to_markdown(), ""]
by_sim = pd.DataFrame({"bucket": pd.cut(nn_sim, [0, .8, .9, .95, .98, 1.01], right=False), "agree": agree}) \
    .groupby("bucket", observed=True).agree.agg(["size", "mean"]).rename(columns={"size": "rows", "mean": "same label"})
out += ["Label agreement with the nearest other row, by similarity:", "", by_sim.round(3).to_markdown(), ""]

# ---------------------------------------------------------------- 3. attribution
collision = nd & (nn_lab != y) & (nn_lab == pred)
rows = []
for c in range(K):
    fn = (y == c) & (pred != c)
    fp = (pred == c) & (y != c)
    for kind, m in (("missed (FN)", fn), ("wrong (FP)", fp)):
        n = m.sum()
        a = (m & collision).sum()
        b = (m & ~collision & issues).sum()
        rows.append({"class": LABELS[c], "error": kind, "n": n,
                     "near-dup collision %": round(a / max(n, 1) * 100, 1),
                     "cleanlab label issue %": round(b / max(n, 1) * 100, 1),
                     "unexplained %": round((n - a - b) / max(n, 1) * 100, 1)})
att = pd.DataFrame(rows)
out += ["## 3. Where the errors come from", "",
        "Each error is assigned to the first matching bucket: (a) a near-duplicate of the row carries the label the "
        "model predicted; (b) cleanlab flags the row's teacher label; (c) unexplained.", "",
        att.to_markdown(index=False), ""]

# ---------------------------------------------------------------- 4. F1 on consistent rows
explained = collision | issues
f_all = f1_score(y, pred, labels=range(K), average=None)
f_cons = f1_score(y[~explained], pred[~explained], labels=range(K), average=None)
f1tab = pd.DataFrame({"F1 all rows": f_all, "F1 rows without collision/issue": f_cons,
                      "rows kept %": [((~explained) & (y == c)).sum() / (y == c).sum() * 100 for c in range(K)]},
                     index=LABELS).round(3)
out += ["## 4. F1 on all rows vs on rows whose teacher label is self-consistent", "",
        f"Rows excluded: {explained.sum()} ({explained.mean():.1%}). This is **not** a holdout estimate (the holdout "
        "keeps its noisy labels); it shows how much of each gap to 0.8 sits on inconsistent labels.", "",
        f1tab.to_markdown(), ""]

# ---------------------------------------------------------------- 5. samples
out += ["## 5. Error samples for the main confusions of the weak classes", ""]
rng = np.random.default_rng(0)
for lab in WEAK:
    c = LABELS.index(lab)
    conf = pd.Series(pred[(y == c) & (pred != c)]).value_counts()
    conf_fp = pd.Series(y[(pred == c) & (y != c)]).value_counts()
    for other, direction, mask in [(conf.index[0], "teacher", (y == c) & (pred == conf.index[0])),
                                   (conf_fp.index[0], "model", (y == conf_fp.index[0]) & (pred == c))]:
        idx = rng.choice(np.flatnonzero(mask), size=min(8, mask.sum()), replace=False)
        title = (f"teacher **{lab}** → model **{LABELS[other]}**" if direction == "teacher"
                 else f"teacher **{LABELS[other]}** → model **{lab}**")
        out += [f"### {title} ({mask.sum()} rows)", ""]
        for i in idx:
            t = train.text.iloc[i].replace("\n", " ")
            tag = " [near-dup collision]" if collision[i] else " [cleanlab issue]" if issues[i] else ""
            out.append(f"- `{i}` p={P[i, y[i]]:.2f}/{P[i, pred[i]]:.2f}{tag}: {t[:260]}{'…' if len(t) > 260 else ''}")
        out.append("")

(REPORTS / "07_error_analysis.md").write_text("\n".join(out))
np.save(DATA / "label_issues.npy", issues)
print("\n".join(out[:120]))
